Kases/urls.py
"""
Definition of urls for Kases.
"""

from datetime import datetime
from django.urls import path
from django.contrib import admin
from django.conf import settings
from django.conf.urls import include
from django.conf.urls import url
from django.contrib.auth import views
#from case.views.case import CaseList
from case.views.case import CaseCreate
from case.views.case import CaseTable
from case.views.case import CaseUpdate
from case.views.case import CaseHome
from case.views.case import CaseDetail
from case.views.case import case_table
from case.views.caseevent import CaseEventUpdate
from case.views.caseevent import CaseEventDetail
from case.views.caseevent import CaseEventCreate
from case.views.caseevent import CaseEventList
from case.views.caseevent import CaseEventHome
from case.views.caseevidence import CaseEvidenceUpdate
from case.views.caseevidence import CaseEvidenceDetail
from case.views.caseevidence import CaseEvidenceCreate
from case.views.caseevidence import CaseEvidenceList
from case.views.caseevidence import CaseEvidenceHome
from case.views.casetask import CaseTaskUpdate
from case.views.casetask import CaseTaskDetail
from case.views.casetask import CaseTaskCreate
from case.views.casetask import CaseTaskList
from case.views.casetask import CaseTaskHome
from case.views.casedevice import CaseDeviceUpdate
from case.views.casedevice import CaseDeviceDetail
from case.views.casedevice import CaseDeviceHome
from case.views.caseentity import CasePersonCreate
from case.views.caseentity import CasePersonUpdate
from case.views.caseentity import CaseEntityHome
from case.views.caseentity import CasePersonDetail
from case.views.caseentity import CaseCompanyCreate
from case.views.caseentity import CaseCompanyUpdate
from case.views.caseentity import CaseCompanyDetail
from inventory.views import InventoryHome
from inventory.views import DeviceCreate
from inventory.views import DeviceDetail
from inventory.views import DeviceUpdate
from loan.views import LoanHome
from loan.views import LoanCreate
from loan.views import LoanDetail
from loan.views import LoanUpdate
from loan.views import LoanCreateWithCase
from loan.views import LoanCreateWithDevice
from loan.views import LoanCreateWithBoth
from loan.views import LoanUpdateWithCase
from loan.views import LoanUpdateWithDevice
from loan.views import LoanUpdateWithBoth
from entity.views.person import person_update
from entity.views.person import person_detail
from entity.views.person import person_add
from entity.views.person import PersonDetail
from entity.views.company import company_edit
from entity.views.company import company_detail
from entity.views.company import company_add
from entity.views.entity import EntityHome
from user.views import update_profile
from utils.forms import BootstrapAuthenticationForm


admin.autodiscover()


urlpatterns = [
    ## Case ##
    path('case/', CaseHome.as_view(), name='cases'), 
    path('case/create/', CaseCreate.as_view(), name='case_create'),
    path('case/<int:pk>/', CaseDetail.as_view(), name='case_detail'),
    path('case/<int:pk>/update/', CaseUpdate.as_view(), name='case_edit'),
    #path('case/list/', CaseList.as_view(), name='case_list'),
    path('case/table/', CaseTable.as_view(), name='casetable'),
    #path('case/table1/', case_table, name='case_table'),
    ## Case Events
    path('case/<int:casepk>/event/', CaseEventHome.as_view(), name='caseevent'),
    path('case/<int:casepk>/event/create/', CaseEventCreate.as_view(), name='caseevent_create'),
    path('case/<int:casepk>/event/<int:pk>/', CaseEventDetail.as_view(), name='caseevent_detail'),
    path('case/<int:casepk>/event/<int:pk>/update/', CaseEventUpdate.as_view(), name='caseevent_update'),
    path('case/<int:casepk>/event/list/', CaseEventList.as_view(), name='caseevent_list'),
    ## Case Evidence
    path('case/<int:casepk>/evidence/', CaseEvidenceHome.as_view(), name='caseevidence'),
    path('case/<int:casepk>/evidence/create/', CaseEvidenceCreate.as_view(), name='caseevidence_create'),
    path('case/<int:casepk>/evidence/<int:pk>/', CaseEvidenceDetail.as_view(), name='caseevidence_detail'),
    path('case/<int:casepk>/evidence/<int:pk>/update/', CaseEvidenceUpdate.as_view(), name='caseevidence_update'),
    path('case/<int:casepk>/evidence/list/', CaseEvidenceList.as_view(), name='caseevidence_list'),
    ## Case Tasks
    path('case/<int:casepk>/task/', CaseTaskHome.as_view(), name='casetask'),
    path('case/<int:casepk>/task/create/', CaseTaskCreate.as_view(), name='casetask_create'),
    path('case/<int:casepk>/task/<int:pk>/', CaseTaskDetail.as_view(), name='casetask_detail'),
    path('case/<int:casepk>/task/<int:pk>/update/', CaseTaskUpdate.as_view(), name='casetask_update'),
    path('case/<int:casepk>/task/list/', CaseTaskList.as_view(), name='casetask_list'),
    ## Case Devices
    path('case/<int:casepk>/device/', CaseDeviceHome.as_view(), name='casedevice'),
    path('case/<int:casepk>/device/<int:pk>/', CaseDeviceDetail.as_view(), name='casedevice_detail'),
    path('case/<int:casepk>/device/<int:pk>/update/', CaseDeviceUpdate.as_view(), name='casedevice_update'),
    ## Case Loans
    path('case/<int:casepk>/loan/', LoanHome.as_view(), name='loanswithcase'),
    path('case/<int:casepk>/inventory/<int:devicepk>/loan/', LoanHome.as_view(), name='loanswithboth'),
    path('case/<int:casepk>/loan/<int:pk>/', LoanDetail.as_view(), name='loanwithcase_detail'),
    path('case/<int:casepk>/inventory/<int:devicepk>/loan/<int:pk>/', LoanDetail.as_view(), name='loanwithboth_detail'),
    path('case/<int:casepk>/loan/create/', LoanCreateWithCase.as_view(), name='loanwithcase_create'),
    path('case/<int:casepk>/loan/update/', LoanUpdateWithCase.as_view(), name='loanwithcase_update'),  
    ## Case Person
    path('case/<int:casepk>/person/', CaseEntityHome.as_view(), name='caseentity'),    
    path('case/<int:casepk>/person/create/', CasePersonCreate.as_view(), name='caseperson_create'),
    path('case/<int:casepk>/person/<int:pk>/', CasePersonDetail.as_view(), name='caseperson_detail'),
    path('case/<int:casepk>/person/<int:pk>/update/', CasePersonUpdate.as_view(), name='caseperson_update'),
    ## Case Company
    path('case/<int:casepk>/company/', CaseEntityHome.as_view(), name='caseentity'),
    path('case/<int:casepk>/company/create/', CaseCompanyCreate.as_view(), name='casecompany_create'),
    path('case/<int:casepk>/company/<int:pk>/', CaseCompanyDetail.as_view(), name='casecompany_detail'),
    path('case/<int:casepk>/company/<int:pk>/update/', CaseCompanyUpdate.as_view(), name='casecompany_update'),
    
    ## Inventory ##
    path('inventory/', InventoryHome.as_view(), name='devices'),
    path('inventory/create/', DeviceCreate.as_view(), name='device_create'),
    path('inventory/<int:pk>/', DeviceDetail.as_view(), name='device_detail'),
    path('inventory/<int:pk>/update/', DeviceUpdate.as_view(), name='device_update'),
    ## Loan with Inventory
    path('inventory/<int:devicepk>/loan/', LoanHome.as_view(), name='loanswithdevice'),
    path('inventory/<int:devicepk>/loan/<int:pk>/', LoanDetail.as_view(), name='loanwithdevice_detail'),    
    path('inventory/<int:devicepk>/case/<int:casepk>/loan/<int:pk>/', LoanDetail.as_view(), name='loanwithboth_detail'),
    path('inventory/<int:devicepk>/loan/create', LoanCreateWithDevice.as_view(), name='loanwithdevice_create'),
    path('inventory/<int:devicepk>/loan/<int:pk>/update', LoanUpdateWithDevice.as_view(), name='loanwithdevice_update'),
    ## Loan
    path('loan/', LoanHome.as_view(), name='loans'),
    path('loan/<int:pk>/', LoanDetail.as_view(), name='loan_detail'),    
    ## Loan Request
    path('loan/create', LoanCreate.as_view(), name='loan_create'),
    path('loan/<int:pk>/update/', LoanUpdate.as_view(), name='loan_update'),    
    ### Return Request

    ## Entity ##
    path('entity/', EntityHome.as_view(), name='entities'),
    ## Entity - Person
    ## TODO change _add to _create   
    path('entity/person/create/', person_add, name='person_add'),
    path('entity/person/<int:pk>/', PersonDetail.as_view(), name='person_detail'),
    path('entity/person/<int:object_id>/update/', person_update, name='person_update'),
    #path('entity/person/<int:object_id>/export/', person_vcard_export, name="person_vcard_export"),
    #path('entity/person/search/', person_search, {'query':None},name='ab_all'),
    ## Entity - Company
    ## TODO change _add to _create
    path('entity/company/create/', company_add, name='company_add'),
    path('entity/company/<int:object_id>/', company_detail, name='company_detail'),
    path('entity/company/<int:object_id>/update/', company_edit, name='company_edit'),
    #path('entity/company/<int:object_id>/export/', company_vcard_export, name="company_vcard_export"),
    #path('entity/company/search/', company_search, {'query':None},name='ab_all'),

    ## User ##
    path('user/', update_profile, name='user'),
    
    ## Needed for Django Authentication ##
    path('accounts/', include('django.contrib.auth.urls')),
    ## Login
    path('login',
        views.login,
        {
            'template_name': 'registration/login.html',
            'authentication_form': BootstrapAuthenticationForm,
            'extra_context':
            {
                'title': 'Log in',
                'year': datetime.now().year,
            }
        },
        name='login'),
    ## Logout
    path('logout',
        views.logout,
        {
            'next_page': '/',
        },
        name='logout'),
  
    ## Admin ##
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),

    ## Base CatchAll ##
    url(r'^$', CaseHome.as_view(), name='home'),
]

# Debug Toolbar
if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path ('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

booking/urls.py
'''
Created on 1/8/2016

@author: luisza
'''
from __future__ import unicode_literals
from django.conf.urls import url
from . import views
from .settings import TOKENIZE

urlpatterns = [
    url(r"^reservation/create$",
        views.CreateReservation.as_view(), name="add_user_reservation"),
    url(r"^reservation/finish$",
        views.finish_reservation, name="finish_reservation"),
    url(r"^reservation/delete_product_reservation/(?P<pk>\d+)$",
        views.deleteProduct, name="delete_product_reservation"),
    url(r"reservation/list", views.ReservationList.as_view(),
        name="reservation_list"),
]

if TOKENIZE:
    urlpatterns += [
        url(r"reservation/token/(?P<pk>\d+)/(?P<token>[0-9a-f-]+)/(?P<status>\d)$",
            views.update_reservation_by_token,
            name="reservation_token")
    ]

booking/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
from django.utils import timezone
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey
from django.utils.translation import ugettext_lazy as _
import uuid

auth_user = settings.AUTH_USER_MODEL if getattr(
    settings, "AUTH_USER_MODEL") else User


class Reservation(models.Model):
    BUILDING = 0
    REQUESTED = 1
    ACCEPTED = 2
    DENIED = 3
    BORROWED = 4
    RETURNED = 5
    STATUS = (
        (BUILDING, _("Building")),
        (REQUESTED, _("Requested")),
        (ACCEPTED, _("Accepted")),
        (DENIED, _("Denied")),
        (BORROWED, _("Borrowed")),
        (RETURNED, _("Returned")),
    )
    user = models.ForeignKey(auth_user)
    reserved_start_date = models.DateTimeField(default=timezone.now)
    reserved_end_date = models.DateTimeField()
    status = models.SmallIntegerField(choices=STATUS, default=BUILDING)
    updated_datetime = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "%s  %s  (%s to %s)" % (self.user.get_full_name(),
                                       self.get_status_display(),
                                       self.reserved_start_date.strftime(
            "%Y/%m/%d %H:%S"),
            self.reserved_end_date.strftime(
            "%Y/%m/%d %H:%S"),
        )


class Product(models.Model):

    reservation = models.ForeignKey(Reservation)
    amount = models.FloatField()
    amount_field = models.CharField(max_length=150)
    borrowed = models.BooleanField(default=False)
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')

    @property
    def available_amount(self):
        return getattr(self.content_object, self.amount_field)

    @property
    def amount_without_this_product(self):
        amount_now = self.available_amount
        return amount_now - self.amount

    def __str__(self):
        return "%.2f ) %s" % (self.amount, self.content_object)


class Observation(models.Model):
    reservation = models.ForeignKey(Reservation)
    text = models.TextField()


class ReservationToken(models.Model):
    reservation = models.ForeignKey(Reservation)
    token = models.UUIDField(default=uuid.uuid4, editable=False)
    base_url = models.URLField(default="http://localhost:8000")

booking/forms.py
# encoding: utf-8

'''
Free as freedom will be 2/9/2016

@author: luisza
'''

from __future__ import unicode_literals

from django import forms
from django.utils.translation import ugettext_lazy as _

from .models import Product, Reservation


class ReservationForm(forms.ModelForm):

    def clean(self):
        if hasattr(self, 'request'):
            if hasattr(self.request, "reservation"):
                raise forms.ValidationError(
                    _("You can not create reservation with active reservation"))
            cleaned_data = super(ReservationForm, self).clean()

    class Meta:
        model = Reservation
        fields = '__all__'
        exclude = ['user', 'status']


class ProductForm(forms.ModelForm):
    model_instance = forms.CharField(widget=forms.HiddenInput)
    available_amount = forms.FloatField(widget=forms.HiddenInput)

    def clean(self):
        cleaned_data = super(ProductForm, self).clean()

        if cleaned_data['amount'] <= 0:
            raise forms.ValidationError(
                _("You amount correct, requested 0 or negative value"))

        if cleaned_data['amount'] > cleaned_data['available_amount']:
            raise forms.ValidationError(
                _("You requested more than product available"))

    class Meta:
        model = Product
        fields = ['amount']

booking/templates/djreservation/product_admin_reservation.html
{% load i18n %}

<table id="products">

	<tr style="background: #79aec8 none repeat scroll 0 0">
		<th><input type="checkbox" name="all" value="uncheck"></th>
		<th> {% trans 'Approves all' %} </th>
	</tr>

	{% for product in instance.product_set.all%}
	<tr>
		<td>
			{% if instance.status == instance.RETURNED  %}
				{% if product.borrowed %}
				{% trans 'Returned' %}
				{%else%}
				{% trans 'Not borrowed' %}
			{% endif %}
			{% else %}
			<input type="checkbox" name="djreservation_product_list" 
			value="{{product.pk}}" {% if product.borrowed %}checked{%endif%} >
			 </td>			
			{% endif %}

		<td>{{product}}</td>
	</tr>

	{% endfor %}
	
</table>


<script>
(function($){ 
  $('input[name="all"]').change(function(){
	if($(this).is(':checked') ){
    	$('#products input').prop( "checked", true );
    }else{
    	$('#products input').prop( "checked", false );
    }
    
    }); 
{% if instance.status == instance.BORROWED %}
  $('#products input').change(function(){
  	 $("#id_status").val({{instance.BORROWED}});
  	$("#id_status option").each(
  		function(i,x){  if( {{instance.BORROWED}} != $(x).val() ){ $(x).remove();  }});
  });
{% endif %}
  $('#id_status').change(function(event){
  		var sel = $(this).find("option:selected").val(); 
    	if(sel == 2){
    		$('#products input').prop( "checked", true );
    	}else if (sel == 3) {
    		$('#products input').prop( "checked", false );
    	}else if(sel == 4){
    		
    	}
    })
    })(django.jQuery)
</script>

booking/templates/djreservation/product_form.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
<form method="post" >
	{% csrf_token %}
	<table class="table">
{{form}}
<tr>
	<td>{% trans "Available:" %}</td>
	<td> {{ available_amount}} </td>
</tr>
{% for field in extra_fields%}
<tr>
	<td>{{field.label}}</td>
	<td>{{field.value}}</td>
</tr>
{%endfor%}
<tr>
	<td></td>
	<td><input class="btn btn-success" type="submit" value="{% trans 'Reserve'%}"></td>
</tr>
</table>
</form>
{%endblock%}

booking/templates/djreservation/reservation_confirm.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
<div class="row">
	 <div class="col-md-8 col-md-offset-2">
	 	
		<form class="form-horizontal" method="post">
			{% csrf_token %} 
			<h2>{% trans 'Are you sure? See above the products details' %}</h2>
			
			<input type="submit"
			class="btn btn-success" value="{% trans 'Finish this reservation' %}" />
		</form>
	</div>
</div>
<div class="row">
 <div class="col-md-8 col-md-offset-1">
 	<h1> {% trans 'Reserved products' %} </h1>
	<ul class="list-group">
		{% for product in reservation.product_set.all %}
  			<li class="list-group-item">
  				{{product}}
<a href="{% url 'delete_product_reservation' product.pk%}" style="position: absolute;right: 15px;" >
  <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
</a>
  			</li>
  			{% empty %}
  			<li class="list-group-item">
  				{% trans "Products are not reserved yet" %}
  			</li>  			
  		{% endfor %}
  	</ul>
 </div>
</div>		

{% endblock %}

booking/templates/djreservation/reservation_finished.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
	<div class="row">
		 <div class="col-md-6 col-md-offset-3">
	{% trans 'Thanks, your reservation was processed successfully' %}
		</div>
	</div>
{% endblock %}

booking/templates/djreservation/reservation_form.html
{% extends 'base.html' %}
{% load static i18n %}

{% block css%} 
  <link rel="stylesheet" type="text/css" media="screen"
     href="{% static 'css/bootstrap-datetimepicker.min.css' %}">
<link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" 
rel="stylesheet">

 <style>
 .bootstrap-datetimepicker-widget{
 	min-width: 250px;
 	width: 270px;
 }
 </style>
 
{%endblock%}


{% block content %}

{% block content_title%}
<h1> {% trans "Creating a reservation"%} </h1>

{% endblock %}
{{form.errors}}
<form class="form-horizontal" method="post">
{% csrf_token %} 

{% block form_start %}{% endblock %}	
	
<div class="form-group">
	{{ form.reserved_start_date.errors }}
	<label id="{{ form.reserved_start_date.id_label_tag }}" class="col-sm-2 control-label" > {% trans 'Reservation start date' %} </label>
<div id="dtp_reserved_start_date" class="input-append date">
	<div class="col-sm-2">							
	      {{ form.reserved_start_date }}
    </div>

	<div class="col-sm-2">
		 <span class="add-on">
	        <i  class="glyphicon glyphicon-calendar"  aria-hidden="true" data-time-icon="icon-time" data-date-icon="icon-calendar"></i>
	      </span>
	</div>
</div>
</div>
	

<div class="form-group">
	{{ form.reserved_end_date.errors }}
	<label id="{{ form.reserved_end_date.id_label_tag }}" class="col-sm-2 control-label" > {% trans 'Reservation end date' %} </label>
<div id="dtp_reserved_end_date" class="input-append date">
	<div class="col-sm-2">							
	      {{ form.reserved_end_date }}
    </div>

	<div class="col-sm-2">
		 <span class="add-on">
	        <i  class="glyphicon glyphicon-calendar"  aria-hidden="true" data-time-icon="icon-time" data-date-icon="icon-calendar"></i>
	      </span>
	</div>
</div>
</div>
{% block form_end %}{% endblock %}	
	
<button type="submit" class="btn btn-default">{% trans 'Submit' %}</button>
</form>

{% endblock %}

{% block js %}
<script type="text/javascript"
     src="{% static 'js/bootstrap-datetimepicker.min.js' %}">
    </script>
    
        <script type="text/javascript">
	      rsd= $('#dtp_reserved_start_date').datetimepicker({
	        format: 'dd/MM/yyyy hh:mm',
	        autoclose: true
	      });
	      rd= $('#dtp_reserved_end_date').datetimepicker({
	        format: 'dd/MM/yyyy hh:mm',
	        autoclose: true
	      });
</script>
    
{% endblock %}

booking/templates/djreservation/reservation_list.html
{% extends 'base.html' %}
{% load static i18n %}

{% block content %}
<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
	{% for reservation in object_list%}

  <div class="panel {% if reservation.status == reservation.REQUESTED %} panel-success {%elif reservation.status == reservation.BORROWED %} panel-danger {%else%}panel-default{%endif%}">
    <div class="panel-heading" role="tab" id="headingOne">
      <h4 class="panel-title">
        <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapse{{reservation.pk}}" aria-expanded="true" aria-controls="collapse{{reservation.pk}}">
 {{reservation}}         
        </a>
      </h4>
    </div>
    <div id="collapse{{reservation.pk}}" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
      <div class="panel-body">
      	<ul class="list-group">
      		{% for product in reservation.product_set.all%}
      			<li class="list-group-item">{{product}}
{% if product.borrowed %}      				
<a href="#" style="position: absolute;right: 15px;" >
  <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
</a>
{%else%}
<a href="#" style="position: absolute;right: 15px;" >
  <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
</a>
{% endif %}	
</li>
		{% endfor%}
</ul>

{% if reservation.observation_set.count %}
<div class="alert alert-info">
	<h2> {% trans 'Observations' %}</h2>
	{% for observation in reservation.observation_set.all %}
		{{observation.text}}
		<hr>
	{% endfor%}
</div>
{% endif %}
      </div>
    </div>
  </div>

	{% empty %}
		 <h2> {% trans 'No reservations saved yet' %}</h2>
	{% endfor %}
</div>


{% if is_paginated %}
	<nav aria-label="...">
		<ul class="pager">
			{% if page_obj.has_previous %}
			<li>
				<a href="?page={{ page_obj.previous_page_number }}">{% trans 'Previous' %}</a>
			</li>
			{% endif %}
	
			<li>
				{% trans 'Page' %} {{ page_obj.number }} -- {{ page_obj.paginator.num_pages }}.
			</li>
	
			{% if page_obj.has_next %}
			<li>
				<a href="?page={{ page_obj.next_page_number }}">{% trans 'Next' %}</a>
			</li>
			{% endif %}
		</ul>
	</nav>

{% endif %}
{% endblock%}

booking/templates/djreservation/simple_reservation.html
{% extends 'djreservation/reservation_form.html'%}
{% load i18n %}


{% block content_title%}
<h1> {% trans "Creating a reservation of :"%} <br><small >{{object}}</small></h1>
{% endblock%}
{% block form_start %}
{{ product_form.non_field_errors }}
  <div class="form-group">
  	{{product_form.amount.errors }}
    <label for="id_amount" class="col-sm-2 control-label">{{product_form.amount.label}}</label>
<div class="col-sm-2">
{{product_form.amount}}
{{product_form.available_amount}}
{{product_form.model_instance}}
</div></div>
  
{% endblock %}	